version: "2"
issues:
  # Maximum issues count per one linter.
  # Set to 0 to disable - unlimited.
  # Default: 50
  max-issues-per-linter: 0
  # Maximum count of issues with the same text.
  # Set to 0 to disable - unlimited.
  # Default: 3
  max-same-issues: 0
linters:
  default: all
  disable:
    - err113
    - exhaustruct
    - funlen
    - interfacebloat
    - lll
    - mnd
    - gocyclo             # using cyclop with the max 30 instead
    - gochecknoglobals
    - gomodguard          # deprecated
    - nlreturn
    - tagalign
    - varnamelen
    - wrapcheck
    - wsl
  settings:
    depguard:
      rules:
        main:
          deny:
            - pkg: github.com/pkg/errors
              desc: Use "standard errors" instead
    unparam:
      check-exported: true
    cyclop:
      max-complexity: 30
  exclusions:
    generated: lax
    rules:
      - linters:
          - funlen  # tests may be long
          - dupword   # tests may contain such
          - goconst   # not critical for tests
          - lll   # tests often require long lines
          - mnd   # tests are full of magic numbers
          - maintidx  # tests may be long
          - testpackage
          - unused  # very annoying false positive: https://github.com/golangci/golangci-lint/issues/791
        path: _test\.go
    paths:
      - third_party$
      - builtin$
      - examples$
      - packaging
formatters:
  enable:
    - gofmt
    - gofumpt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/percona/telemetry-agent
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
      - packaging
