version: "2"
issues:
  # Maximum issues count per one linter.
  # Set to 0 to disable - unlimited.
  # Default: 50
  max-issues-per-linter: 0
  # Maximum count of issues with the same text.
  # Set to 0 to disable - unlimited.
  # Default: 3
  max-same-issues: 0
linters:
  default: all
  disable:
    - err113
    - exhaustruct
    - funlen
    - interfacebloat
    - lll
    - mnd
    - nlreturn
    - tagalign
    - varnamelen
    - wrapcheck
    - wsl
  settings:
    depguard:
      rules:
        main:
          deny:
            - pkg: github.com/pkg/errors
              desc: Use "standard errors" instead
    unparam:
      check-exported: true
  exclusions:
    generated: lax
    rules:
      - linters:
          - funlen
          - testpackage
          - unused
        path: _test\.go
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - gofumpt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/percona/telemetry-agent
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
