#!/bin/bash

set -e

if [ -f /usr/share/debconf/confmodule ]; then
    . /usr/share/debconf/confmodule
fi

case "$1" in
	remove)
	if [ -x "/bin/systemctl" ]; then
		systemctl daemon-reload > /dev/null 2>&1 || :
	fi
	groupdel percona-telemetry || true
	;;

	purge | upgrade | failed-upgrade | abort-install | abort-upgrade | disappear) ;;

	*)
	echo "postrm called with unknown argument '$1'" 1>&2
	exit 1
	;;
esac

#DEBHELPER#

exit 0
