#!/bin/bash

set -e
# Stop the service if it's running
if [ -x "/bin/systemctl" ]; then
    echo "Stopping Percona Telemetry Agent service..."
    /bin/systemctl stop percona-telemetry-agent.service > /dev/null 2>&1 || :
fi

set +e

exit 0
